version: "3.9"
services:
  redis:
    image: "redis:alpine"
    network_mode: host
  test-server:
    image: ghcr.io/linuxserver/openssh-server
    ports:
    - 2222:2222
    environment:
      - SUDO_ACCESS=true #optional
      - PASSWORD_ACCESS=true #optional
      - USER_PASSWORD=password #optional
      - USER_NAME=username #optional
