import Head from 'next/head';
import Logo from '../svg/logo.svg';
import DotPattern from '../svg/dot-pattern.svg';
import Link from 'next/link';
import Image from 'next/image';

export default function Home() {
  return (
    <>
      <Head>
        <title>SuperCompose</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;800&display=swap"
          rel="stylesheet"
        />
        {/* <link
          href="https://fonts.googleapis.com/css2?family=Inter"
          rel="stylesheet"
        /> */}
      </Head>
      <div
        className="absolute w-full h-full select-none pointer-events-none m-0 p-0 top-0"
        style={{ zIndex: -1 }}
      >
        <DotPattern className="absolute right-0 top-0" style={{ zIndex: -1 }} />
        <DotPattern
          className="absolute left-0"
          style={{ zIndex: -1, top: 500 }}
        />
      </div>
      <nav className="flex flex-row items-center m-auto mt-2.5 max-w-[1200px]">
        <a href="/">
          <Logo height={44} />
        </a>
        <div className="flex-grow" />
        <div>
          <a
            className="font-medium text-md text-gray-500 m-5"
            href="https://github.com/jkelin/supercompose"
            target="_blank"
          >
            GitHub
          </a>
          <a
            className="font-medium text-md text-gray-500 m-5"
            href="https://docs.supercompose.net"
          >
            Documentation
          </a>
          <Link href="/rationale">
            <a className="font-medium text-md text-gray-500 m-5">But Why?</a>
          </Link>
        </div>
        <div className="flex-grow" />
        <a
          href="https://app.supercompose.net/api/login"
          className="inline-flex items-center px-4 py-2 border border-transparent text-md bg-white font-medium rounded shadow text-indigo-600 hover:bg-indigo-600 hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
        >
          Log in
        </a>
      </nav>
      <main>
        <section className="text-center max-w-[774px] m-auto mt-12">
          <div className="font-extrabold text-[60px] leading-[60px]">
            <span className="text-gray-900">Manage your servers</span>
            <br />
            <span className="text-indigo-600">the easy way</span>
          </div>
          <div className="mt-5 text-xl text-gray-500">
            Use docker-compose from a web UI to manage applications on your
            servers. Choose simple tech that you already know instead of
            complicating things.
          </div>
          <a
            href="https://app.supercompose.net/api/register"
            className="inline-flex items-center mt-5 px-5 py-4 border border-transparent text-md bg-indigo-600 font-medium rounded-lg shadow text-white hover:bg-indigo-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
          >
            Get started - it’s free
          </a>
          <div className="mt-5 text-gray-500 text-sm">Currently in ALPHA</div>
        </section>
        <section className="relative mt-6">
          <div className="absolute w-full top-[270px] left-0 bg-gray-800 h-[280px]"></div>
          <div className="flex justify-center">
            <div className="relative w-[640px] h-[464px]">
              <div className="hidden lg:block absolute bottom-[14px] lg:left-[-150px] xl:left-[-282px] rounded-lg shadow-landing h-[285px]">
                <Image
                  src="/img/ss-node.png"
                  alt="Picture of SuperCompose node"
                  className="rounded-lg"
                  width={397}
                  height={285}
                  quality={95}
                  priority={true}
                />
              </div>

              <div className="hidden lg:block absolute bottom-[14px] lg:right-[-150px] xl:right-[-282px] rounded-lg shadow-landing h-[285px]">
                <Image
                  src="/img/ss-compose.png"
                  alt="Picture of SuperCompose compose"
                  className="rounded-lg"
                  width={397}
                  height={285}
                  quality={95}
                  priority={true}
                />
              </div>

              <div className="absolute top-0 left-0 rounded-lg shadow-landing h-[464px]">
                <Image
                  src="/img/ss-deployment.png"
                  alt="Picture of SuperCompose deployment"
                  className="rounded-lg"
                  width={640}
                  height={464}
                  quality={95}
                  priority={true}
                />
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
