version: "3.9"
services:
  redis:
    image: "bitnami/redis:latest"
    network_mode: host
    volumes:
      - redis-data:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  postgres:
    image: bitnami/postgresql:13
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_database=supercompose

    
volumes:
  postgres-data:
  redis-data: