version: "3.0"
services:
  frontend:
    build: ../../frontend
    ports:
      - 3100:3000
    environment:
      - BACKEND_URI
      - AUTH0_SECRET
      - AUTH0_BASE_URL
      - AUTH0_ISSUER_BASE_URL
      - AUTH0_CLIENT_ID
      - AUTH0_AUDIENCE
      - AUTH0_CLIENT_SECRET
      - PANELBEAR_SITE_ID
    logging:
      driver: json-file
      options:
        max-size: 100m
    restart: always

  backend:
    build: ../../backend/SuperCompose
    ports:
      - 3101:80
    environment:
      - ConnectionStrings__SupercomposeContext
      - ConnectionStrings__KeysContext
      - ConnectionStrings__Redis
      - ConnectionStrings__Jaeger=udp://jaeger:6831
      - Proxy__Url=http://proxy:8080
      - Proxy__JWT
      - SENTRY_DSN
      - Auth__Authority
      - Auth__Audience
      - ASPNETCORE_ENVIRONMENT
      - Seq__ServerUrl=http://seq:5341
    logging:
      driver: json-file
      options:
        max-size: 100m
    restart: always

  proxy:
    build: ../../proxy
    environment:
      - JWT_KEY=$Proxy__JWT
      - JAEGER_URL=http://jaeger:14268/api/traces
    logging:
      driver: json-file
      options:
        max-size: 100m
    restart: always

  seq:
    image: datalust/seq:2021.2
    ports:
      - 5341:5341
      - 5342:80
    volumes:
      - seq-data:/data
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH

  jaeger:
    image: jaegertracing/opentelemetry-all-in-one
    environment:
      - "SPAN_STORAGE_TYPE=badger"
      - "BADGER_EPHEMERAL=false"
      - "BADGER_DIRECTORY_VALUE=/badger/data"
      - "BADGER_DIRECTORY_KEY=/badger/key"
    volumes:
      - jaeger-data:/badger
    ports:
      - "16686:16686"

volumes:
  redis-data:
  seq-data:
  jaeger-data:
