version: "3.0"
services:
  frontend:
    build: ../../frontend
    ports:
      - 3100:3000
    environment:
      - BACKEND_URI
    logging:
      driver: json-file
      options:
          max-size: 100m
    restart: always
  backend:
    build: ../../backend
    ports:
      - 3101:80
    environment:
      - ConnectionStrings__SupercomposeContext
      - ConnectionStrings__KeysContext
      - ConnectionStrings__Redis
      - Sentry_Dsn
    logging:
      driver: json-file
      options:
          max-size: 100m
    restart: always
volumes:
  redis-data: