version: "3.0"
services:
  frontend:
    build: ../../frontend
    ports:
      - 3100:3000
    environment:
      - BACKEND_URI
      - AUTH0_SECRET
      - AUTH0_BASE_URL
      - AUTH0_ISSUER_BASE_URL
      - AUTH0_CLIENT_ID
      - AUTH0_AUDIENCE
      - AUTH0_CLIENT_SECRET
      - PANELBEAR_SITE_ID
    logging:
      driver: json-file
      options:
        max-size: 100m
    restart: always

  backend:
    build: ../../backend/SuperCompose
    ports:
      - 3101:80
    environment:
      - ConnectionStrings__SupercomposeContext
      - ConnectionStrings__KeysContext
      - ConnectionStrings__Redis
      - SENTRY_DSN
      - Auth__Authority
      - Auth__Audience
      - ASPNETCORE_ENVIRONMENT
      - Seq__ServerUrl=http://seq:5341
    logging:
      driver: json-file
      options:
        max-size: 100m
    restart: always

  seq:
    image: datalust/seq:2021.2
    ports:
      - 5341:5341
      - 5342:80
    volumes:
      - seq-data:/data
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH
volumes:
  redis-data:
  seq-data:
